services:
    truffle:
        build:
            context: .
            dockerfile: Dockerfile
            target: truffle-dev
        container_name: truffle
        ports:
            - target: 80
              published: 8001
            - target: 9545
              published: 9545
        volumes:
            - type: bind
              source: solidity
              target: /battle
    vue:
        build:
            context: .
            dockerfile: Dockerfile
            target: vue
        container_name: vue
        ports:
            - target: 8000
              published: 8000
        volumes:
            - type: bind
              source: vue
              target: /battle
